server:
  port: 6970
  name: "dream-vue-admin"
  logPath: "./logs"
  logLevel: "debug"

database:
  ip: "192.168.192.170"
  port: 3306
  username: "root"
  password: "root"
  database: "dream-vue-admin"

redis:
  ip: "192.168.192.170"
  port: 6379
  password: ""
  database: 0

jwt:
  secretKey: "dream-vue-admin&dpengchen@163.com"
  expire: 31