// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "{{.TermsOfService}}",
        "contact": {
            "name": "{{.Contact.Name}}",
            "url": "{{.Contact.URL}}",
            "email": "{{.Contact.Email}}"
        },
        "license": {
            "name": "{{.License.Name}}",
            "url": "{{.License.URL}}"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/system/dict": {
            "post": {
                "description": "创建一个新的字典项",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "字典管理"
                ],
                "summary": "创建字典",
                "parameters": [
                    {
                        "description": "字典信息",
                        "name": "dict",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/system_model.Dict"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            },
            "delete": {
                "description": "根据ID列表删除字典项",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "字典管理"
                ],
                "summary": "删除字典",
                "parameters": [
                    {
                        "description": "字典ID列表",
                        "name": "ids",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "integer"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/system/dict/list": {
            "get": {
                "description": "根据条件查询字典列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "字典管理"
                ],
                "summary": "查询字典列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "字典名称",
                        "name": "dictName",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "每页数量",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/system/dict/{id}": {
            "get": {
                "description": "根据ID获取字典详情",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "字典管理"
                ],
                "summary": "获取字典详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "字典ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            },
            "put": {
                "description": "根据ID修改字典信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "字典管理"
                ],
                "summary": "修改字典",
                "parameters": [
                    {
                        "type": "string",
                        "description": "字典ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "字典信息",
                        "name": "dict",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/system_model.Dict"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "core.DreamModel": {
            "type": "object",
            "properties": {
                "createBy": {
                    "description": "创建人",
                    "type": "integer"
                },
                "createByNickname": {
                    "description": "创建人",
                    "type": "string"
                },
                "createTime": {
                    "type": "string"
                },
                "deleteBy": {
                    "description": "删除人",
                    "type": "integer"
                },
                "deleteByNickname": {
                    "description": "删除人",
                    "type": "string"
                },
                "deleteTime": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "isDel": {
                    "description": "软删除",
                    "type": "boolean"
                },
                "updateBy": {
                    "description": "创建人",
                    "type": "integer"
                },
                "updateByNickname": {
                    "description": "创建人",
                    "type": "string"
                },
                "updateTime": {
                    "type": "string"
                }
            }
        },
        "response.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "msg": {
                    "type": "string"
                }
            }
        },
        "system_model.Dict": {
            "type": "object",
            "properties": {
                "createBy": {
                    "description": "创建人",
                    "type": "integer"
                },
                "createByNickname": {
                    "description": "创建人",
                    "type": "string"
                },
                "createTime": {
                    "type": "string"
                },
                "deleteBy": {
                    "description": "删除人",
                    "type": "integer"
                },
                "deleteByNickname": {
                    "description": "删除人",
                    "type": "string"
                },
                "deleteTime": {
                    "type": "string"
                },
                "dictCode": {
                    "type": "string"
                },
                "dictName": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "isDel": {
                    "description": "软删除",
                    "type": "boolean"
                },
                "updateBy": {
                    "description": "创建人",
                    "type": "integer"
                },
                "updateByNickname": {
                    "description": "创建人",
                    "type": "string"
                },
                "updateTime": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/v1",
	Schemes:          []string{"http"},
	Title:            "Dream Vue Admin API",
	Description:      "这是一个基于Gin框架的API服务",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}